Feature/arseny models
ZUS666/spot pull request #4
Opened 2023-09-15 17:41 UTC by Arseny13

Добавил основные эндпойнты и модели. Как только появится более подробная информация, какое должно быть тело запроса и ответ , исправлю. У модели order скоро попытюась сделать таски, чтобы менять статус.

2023-09-16 07:11 UTC, ZUS666 requested changes

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/api/views/favorite.py
> +    def get_location(self):
впринципе норм, но мой ревьюер говорил получать это через сериализатор и скрытые поля. Можешь посмотреть в foodgram там тоже есть добавление в избранное

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/api/views/order.py
> +    serializer_class = OrderSerializer
queryset = Order.objects.all()

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/api/views/order.py
> +        return Order.objects.filter(user=self.request.user)
а тут через super().get_queryset().filter()

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/api/views/order.py
> +        return Order.objects.filter(user=self.request.user)
развернутое объяснение почему так могу переслать в телегу

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/spots/models/spot.py
> +    name = models.TextField(
вроде с полями определились

2023-09-16 07:11 UTC, ZUS666 commented on api_spot/spots/models/spot.py
> +    name = models.TextField(
name = models.CharField

2023-09-16 13:54 UTC, Arseny13 commented on api_spot/api/permissions.py
> +class IsReadOnly(BasePermission):
Исправил.

2023-09-16 13:54 UTC, Arseny13 commented on api_spot/api/serializers/favorite.py
> +    def validate(self, data):
Исправил.

2023-09-16 13:54 UTC, Arseny13 commented on api_spot/api/serializers/order.py
> +        """Проверка на повтор."""
Исправил.

2023-09-16 13:55 UTC, Arseny13 commented on api_spot/api/serializers/order.py
> +    def get_duration(self, obj):
Исправил.

2023-09-16 13:57 UTC, Arseny13 commented on api_spot/api/serializers/order.py
> +            raise serializers.ValidationError(
В clean модель добавил. ValidationError оставил. ValueError это же базовый в python, я не думаю что он тут подходит.

2023-09-16 13:57 UTC, Arseny13 commented on api_spot/api/serializers/review.py
> +    name = StringRelatedField(source="user.first_name", read_only=True)
Исправил.

2023-09-16 13:58 UTC, Arseny13 commented on api_spot/api/views/favorite.py
> +    def get_location(self):
У Favorite и Order сделал через скрытые поля.

2023-09-16 13:59 UTC, Arseny13 commented on api_spot/api/views/order.py
> +    serializer_class = OrderSerializer
Исправил.

2023-09-16 13:59 UTC, Arseny13 commented on api_spot/api/views/order.py
> +        return Order.objects.filter(user=self.request.user)
Исправил.

2023-09-16 13:59 UTC, Arseny13 commented on api_spot/spots/models/spot.py
> +    name = models.TextField(
Исправил.

2023-09-17 18:27 UTC, ZUS666 commented on api_spot/spots/models/review.py
> +        validators=(MinValueValidator(1), MaxValueValidator(5)),
я за отдельный файл

2023-09-18 14:50 UTC, ZUS666 reviewed
добавил несколько комментов

2023-09-18 18:47 UTC, ZUS666 approved these changes

2023-09-19 09:15 UTC, merged