Fix/model arseny
ZUS666/spot pull request #8
Opened 2023-09-19 12:02 UTC by Arseny13

Изменил модель order + изменил константы. 
У order.count_people есть закоменченый валидатор, когда у spot будет поле max_count доделаю. 
Хотя не очень понимаю как это должно выглядить работать. Вот у нас есть спот у него максимальное количество 100 . 
Есть несколько заказов на этот спот с разным количество людей и с разным временем .  Какая должна быть валидация?

2023-09-19 12:03 UTC, Arseny13 commented on api_spot/spots/models/__init__.py
>  Location
Для чего они тут нужны ?

2023-09-19 12:45 UTC, ZUS666 commented on api_spot/spots/models/__init__.py
>  Location
не помню, вроде не нужны. единственное надо добавить в setup.cfg чтобы flake8 не ругался, что импорты не используются

2023-09-19 12:45 UTC, ZUS666 commented on api_spot/spots/models/favorite.py
> +    pub_date = models.DateField(
а нам вообще это поле для чего? дата, когда добавлено в избранное?

2023-09-19 12:45 UTC, ZUS666 commented on api_spot/spots/models/order.py
> +    time = MultiSelectField(
не понятно, но очень интересно)

2023-09-19 12:45 UTC, ZUS666 commented on requirements.txt
>  celery
в доке селери есть такой вариант celery[redis]

2023-09-19 12:45 UTC, ZUS666 commented on api_spot/api/tasks.py
> +    sleep(settings.TIME_CHANGE_STATUS)
таску можно вызвать с отложенным стартом аргумент что-то типа countdown при вызове. если это сейчас просто для проверки то ок.

2023-09-19 12:45 UTC, ZUS666 commented on api_spot/spots/models/order.py
> +    count_people = models.IntegerField(
не очень представляю как эту будет работать. Может при заказе просто бронить количество спотов.
То есть например создаем Location в нем создаем 10 Spot. И при заказе просто бронить несколько Spot. и получится, что есть несколько бронирований. плюс можно будет отменять их отдельно.
а в Location показывать количество этих спотов свободных. При фильтре по времени показывать. тоже самое только те которые не забронированы в это время

2023-09-19 14:29 UTC, Arseny13 commented on api_spot/spots/models/__init__.py
>  Location
я про то что можно же просто # noqa написать, не ?

2023-09-19 14:46 UTC, Arseny13 commented on api_spot/api/tasks.py
> +    sleep(settings.TIME_CHANGE_STATUS)
Могу сделать через countdown, но в доке сказано что `Therefore, using eta and countdown is not recommended for scheduling tasks for a distant future. Ideally, use values no longer than several minutes. For longer durations, consider using database-backed periodic tasks, e.g. with [django-celery-beat](https://pypi.python.org/pypi/django-celery-beat/) if using Django` Поэтому через sleep cделал.

2023-09-19 15:02 UTC, Arseny13 commented on api_spot/spots/models/order.py
> +    count_people = models.IntegerField(
Понял, тогда поле count_people уберу.

2023-09-19 19:29 UTC, ZUS666 commented on api_spot/api/tasks.py
> +    sleep(settings.TIME_CHANGE_STATUS)
ну distant future тут понятие растяжимое, пол часа те же наверно не сильно отдаленное будущее. мне кажется тут для задач по расписанию. к примеру раз в неделю что либо делать и тут селери бит более подходящий вариант. но это все не точно

2023-09-19 20:16 UTC, ZUS666 requested changes
ответь по валидации order

2023-09-19 20:16 UTC, ZUS666 commented on api_spot/spots/models/order.py
> +            if intersection:
если знаешь как это реализовать чтобы api работало нормально со всеми фильтрами по времени и выводом забронированных и свободных вариантов то ок. но я сейчас так сразу не могу понять как вообще рабоать с этим полем.

2023-09-19 21:08 UTC, Arseny13 commented on api_spot/spots/models/order.py
> +            if intersection:
Ну по сути , эта валидация работает значит у нас в бд есть только заказы с разными промежутками времени.  
Для сериализатора аналогичную валидацию написать тоже можно, но она трудозатратная( а как без циклов сделать не знаю)(хотя циклы максмум из 12 только). 

MultiSelectField в бд хранится как строка и значения через запятую ( то есть в данном случем если три врмени например 8:00 9:00 12:00, то в бд хранится так 8:00,9:00,12:00.) 

Насчет фильтрации: по дате и споту находим все заказы и формируем список свободных времени.  Ну мне тоже при start_time и end_time было проще понимать что и как.

2023-09-19 21:10 UTC, Arseny13 commented on api_spot/spots/models/order.py
> +            if intersection:
Вообще можно отдельную модель  m2m создать TimeSpot. и  с ней рабоать. Думаю так понятнее будет, хотя не факт.

2023-09-20 10:31 UTC, Arseny13 commented
Вернул start time and end time. Убрал multuchoices

2023-09-20 13:16 UTC, ZUS666 approved these changes

2023-09-20 13:51 UTC, merged