Feature/task beat
ZUS666/spot pull request #83
Opened 2023-09-29 21:32 UTC by Arseny13

вроде работате LUL

2023-09-29 21:46 UTC, ZUS666 requested changes

2023-09-29 21:46 UTC, ZUS666 commented on api_spot/spots/tasks.py
> +    """Периодичная заадача, которая завершает заказы который закончились."""
опечатка

2023-09-29 21:46 UTC, ZUS666 commented on api_spot/spots/tasks.py
> +    return "Статусы заказов, которые прошли закрились"
опечатка

2023-09-29 21:46 UTC, ZUS666 commented on api_spot/spots/tasks.py
> +    orders = Order.objects.filter(
что если по сразу по  date и end_time фильтровать и в цикле не проверять date_finish?

2023-09-29 21:46 UTC, ZUS666 commented on api_spot/api_spot/celery.py
> +        'schedule': crontab(hour=0, minute=0),
почему 0 0
кажется надо что-то типа minute=X, hour='*/1'
X = что то в районе 2-5 минут хз нужна ли такая погрешность

2023-09-30 07:37 UTC, Arseny13 commented on api_spot/api/views/order.py
> +    http_method_names = ('post', 'patch')
Убрал update  и изменил отмену на patch

2023-09-30 07:39 UTC, Arseny13 commented on api_spot/spots/tasks.py
> +    orders = Order.objects.filter(
Сделал как ты предложил. Но я думал главная идея была просто запускать задачу раз в день чтобы смотреть какие задачи не закрылись( если не сработала задача api.close_order). А так как будто close_order бесполезная.

2023-09-30 09:09 UTC, ZUS666 commented on api_spot/spots/tasks.py
> +    orders = Order.objects.filter(
задача которая до этого была как мне кажется не совсем подходит. типа у нас возомжна бронь за 2 месяца вперед. получается задача эта будет висеть 2 месяца. а если таких задач будет много. а эта задача которая раз в час закрывает завершенные задачи. но это все не точно)

2023-09-30 09:28 UTC, ZUS666 commented on api_spot/spots/tasks.py
> +    orders = Order.objects.filter(
типа ту задачу надо убрать и оставить только по расписанию как мне кажется

2023-09-30 11:16 UTC, Arseny13 commented on api_spot/spots/tasks.py
> +    orders = Order.objects.filter(
Cогласен, убрал сlose task

2023-09-30 12:36 UTC, ZUS666 approved these changes

2023-09-30 12:37 UTC, merged