Внесены изменения в модели и исправлены ошибки после ревью.
ZUS666/spot pull request #9
Opened 2023-09-19 13:32 UTC by Zolibot

Внесены изменения в модели
Добавлены административные панели
Исправлены импорты
Исправлены ошибки, выявленные в процессе ревью

2023-09-19 17:40 UTC, Arseny13 approved these changes

2023-09-19 20:08 UTC, ZUS666 requested changes

2023-09-19 20:08 UTC, ZUS666 commented on api_spot/spots/models/equipment.py
> +class Equipment(models.Model):
промежуточная модель будет автоматически создана? я за явную.

2023-09-19 20:29 UTC, ZUS666 requested changes

2023-09-19 20:29 UTC, ZUS666 commented on requirements.txt
> +phonenumbers==8.13.20
я думал это у меня что-то криво встает. видимо нет
допольнительно устанавливал по этой доке
https://django-phonenumber-field.readthedocs.io/en/latest/
django-phonenumber-field[phonenumberslite]

2023-09-19 20:29 UTC, ZUS666 commented on api_spot/api_spot/settings.py
> +    'phonenumber_field',
не понял почему так.

2023-09-20 05:29 UTC, ZUS666 commented on api_spot/api_spot/settings.py
> +    'phonenumber_field',
меняем библиотеку на другую?

2023-09-20 09:05 UTC, ZUS666 approved these changes

2023-09-20 09:05 UTC, merged