fix: Update settings.py
ZUS666/spot pull request #97
Opened 2023-10-04 19:58 UTC by Arseny13

fix csrf

2023-10-04 20:33 UTC, ZUS666 requested changes
default надо исправить тогда

2023-10-05 08:57 UTC, ZUS666 commented on api_spot/api_spot/settings.py
> +    'http://' + os.getenv('HOST', default='http://'+'85.41.160.27')
из дефолта надо убрать http://
сейчас получается если в env нет хоста, то http://http://

2023-10-05 09:48 UTC, Arseny13 commented on api_spot/api_spot/settings.py
> +    'http://' + os.getenv('HOST', default='http://'+'85.41.160.27')
дефолты убрать норм идея. ( по всему приложению)

2023-10-06 09:09 UTC, ZUS666 approved these changes

2023-10-06 09:10 UTC, merged